default:
  timeout: 10
  retries: 3

environments:
  local:
    base_url: "http://localhost:3000.example"
  dev:
    base_url: "https://serverest.dev"
  hml:
    base_url: "https://hml.serverest.dev.example"

current_env: "dev"