[project]
name = "sdet-python-automation-core"
version = "0.0.1"
description = "Reusable automation core for SDET projects"
readme = "README.md"
requires-python = ">=3.9"
authors = [
  { name="Rodrigo Trombeta", email="rftrombeta@gmail.com" }
]

dependencies = [
  "robotframework>=6.0",
  "requests>=2.31",
  "pyyaml>=6.0"
]

[project.optional-dependencies]
dev = [
  "pytest",
  "black",
  "ruff",
  "mypy"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
